name: Demo pull with tags

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull from Lokalise
        uses: lokalise/lokalise-pull-action@v0.1.0
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 5240680466981cdb8c9717.46827333
          translations_path: locales
          file_format: json
          additional_params: --filter-data translated
          temp_branch_prefix: l10n-
            