name: Updated XML Demo push with tags
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: lokalise/lokalise-push-action@v4.0.0
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 728044426499ab4e96ee46.18204254
          base_lang: en
          translations_path: |
            g11n/data/src/main/res/values
          name_pattern: strings.xml
          file_format: xml
          rambo_mode: true
          skip_default_flags: false
          skip_tagging: false
          additional_params: 
            

