name: Updated XML Demo pull with tags

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull from Lokalise
        uses: lokalise/lokalise-pull-action@v4.0.0
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 728044426499ab4e96ee46.18204254
          translations_path: |
            g11n/data/src/main/res/values
          file_format: xml
          force_push: true
          skip_include_tags: true
          post_process_command: |
            set -euo pipefail

            # Lokalise TRANSLATIONS_PATH env variable
            translations_path="${TRANSLATIONS_PATH:-g11n/data/src/main/res/values}"

            old_dir="$translations_path/b+es+419"
            new_dir="$(dirname "$translations_path")/values-b+es+419"

            if [ -d "$old_dir" ]; then
                echo "Renaming $old_dir -> $new_dir"

                # Ensure parent exists
                mkdir -p "$(dirname "$new_dir")"

                # Rename folder (moves contents)
                mv "$old_dir" "$new_dir"

                # Update Git index so commit script sees the new path
                git add "$new_dir"
                git rm -r --cached "$old_dir" || true

                echo "Spanish folder rename staged for commit."
            else
                echo "No Spanish folder found at $old_dir"
            fi
          additional_params: >
            {
              "language_mapping": [
                {"original_language_iso": "es", "custom_language_iso": "b+es+419"}
                ]
            }