name: Updated XML Demo pull with tags

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull from Lokalise
        uses: lokalise/lokalise-pull-action@v4.0.0
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 728044426499ab4e96ee46.18204254
          translations_path: |
            g11n/data/src/main/res/values
          file_format: xml
          skip_include_tags: true
          post_process_command: |
            old_dir="g11n/data/src/main/res/values/b+es+419"
            new_dir="g11n/data/src/main/res/values-b+es+419"

            if [ -d "$old_dir" ]; then
                # Make sure parent exists
                mkdir -p "$(dirname "$new_dir")"
                # Rename folder (moves contents too)
                mv "$old_dir" "$new_dir"
                git add "$new_dir"
                git rm -r --cached "$old_dir" || true
            fi


          additional_params: >
            {
              "language_mapping": [
                {"original_language_iso": "es", "custom_language_iso": "b+es+419"}
              ]
            }